CREATE TABLE Accounts(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IBAN NVARCHAR(MAX) NOT NULL,
	Balance decimal(18,2) NOT NULL,
	Currency INT NOT NULL,
	PersonId NVARCHAR(450) NOT NULL,

	FOREIGN KEY (PersonId)
	REFERENCES AspNetUsers(Id)
)